# Generated by Django 5.2.1 on 2025-05-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_enquiry_recaptchatoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='recaptchaToken',
            field=models.CharField(max_length=2000),
        ),
    ]
