# Generated by Django 5.2.1 on 2025-05-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_enquiry_recaptchatoken'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['created_at'], name='contact_enq_created_b6ecb0_idx'),
        ),
    ]
