# Generated by Django 5.2.1 on 2025-08-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyenquiry',
            name='assigned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='surveyenquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveyenquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
